import Image from 'next/image';

/**
 * The Nexora badge, matching the app icon and the browser tab.
 *
 * The whole badge rather than the N on its own: the N is white and cyan, so it
 * vanishes against the admin's light theme. Carrying its own ground means one
 * asset works on both themes — which is also why this no longer inherits
 * currentColor the way the old flat mark did.
 *
 * Regenerated by scripts/generate-icons.mjs; do not hand-edit the PNG.
 */
export function NexoraMark({ className }: { className?: string }) {
  return (
    <Image
      src="/nexora-mark.png"
      alt=""
      aria-hidden
      width={256}
      height={256}
      // Rendered at 24–40px, so the 256px source is well past retina and never
      // needs the optimiser.
      unoptimized
      className={className}
    />
  );
}
